const guides=[
{title:'卢浮宫',country:'france',city:'巴黎',file:'卢浮宫-中文语音导览-详细版.mp3'},{title:'奥赛博物馆',country:'france',city:'巴黎',file:'奥赛博物馆-中文语音导览-详细版.mp3'},{title:'橘园美术馆',country:'france',city:'巴黎',file:'橘园美术馆-中文语音导览-详细版.mp3'},{title:'巴黎罗丹美术馆',country:'france',city:'巴黎',file:'巴黎罗丹美术馆-中文语音导览-详细版.mp3'},{title:'巴黎荣军院',country:'france',city:'巴黎',file:'巴黎荣军院-中文语音导览-详细版.mp3'},{title:'巴黎圣母院',country:'france',city:'巴黎',file:'巴黎圣母院-中文语音导览-详细版.mp3'},{title:'圣心堂与蒙马特',country:'france',city:'巴黎',file:'巴黎-圣心堂与蒙马特-中文语音导览.mp3'},
{title:'阿尔罕布拉宫',country:'spain',city:'格拉纳达',file:'阿尔罕布拉宫-中文语音导览-详细版.mp3'},{title:'圣赫罗尼莫修道院',country:'spain',city:'格拉纳达',file:'格拉纳达圣赫罗尼莫修道院-中文语音导览-详细版.mp3'},{title:'圣家堂',country:'spain',city:'巴塞罗那',file:'圣家堂-中文语音导览.mp3'},{title:'桂尔公园',country:'spain',city:'巴塞罗那',file:'桂尔公园-中文语音导览-详细版.mp3'},{title:'巴塞罗那桂尔宫',country:'spain',city:'巴塞罗那',file:'巴塞罗那桂尔宫-中文语音导览-详细版.mp3'},{title:'巴特略之家',country:'spain',city:'巴塞罗那',file:'巴特略之家-中文语音导览-详细版.mp3'},{title:'米拉之家',country:'spain',city:'巴塞罗那',file:'米拉之家-中文语音导览-详细版.mp3'},{title:'圣保罗医院',country:'spain',city:'巴塞罗那',file:'圣保罗医院-中文语音导览-详细版.mp3'},{title:'加泰罗尼亚音乐宫',country:'spain',city:'巴塞罗那',file:'加泰罗尼亚音乐宫-中文语音导览-详细版.mp3'},{title:'巴塞罗那毕加索博物馆',country:'spain',city:'巴塞罗那',file:'巴塞罗那毕加索博物馆-中文语音导览-详细版.mp3'},
{title:'马德里王宫',country:'spain',city:'马德里',file:'马德里王宫-中文语音导览-详细版.mp3'},{title:'普拉多博物馆',country:'spain',city:'马德里',file:'普拉多博物馆-中文语音导览-详细版.mp3'},{title:'索菲亚王后国家艺术中心',country:'spain',city:'马德里',file:'索菲亚王后国家艺术中心-中文语音导览-详细版.mp3'},{title:'提森国立博物馆',country:'spain',city:'马德里',file:'提森国立博物馆-中文语音导览-详细版.mp3'},{title:'塞维利亚大教堂',country:'spain',city:'塞维利亚',file:'塞维利亚大教堂-中文语音导览-详细版.mp3'},{title:'塞维利亚王宫',country:'spain',city:'塞维利亚',file:'塞维利亚王宫-中文语音导览-详细版.mp3'}];
const $=id=>document.getElementById(id),audio=$('audio'),OFFLINE_CACHE='travel-audio-guide-audio-v1';
const state={country:'all',city:'all',query:'',current:null,favorites:new Set(JSON.parse(localStorage.getItem('tour-favorites')||'[]')),recent:JSON.parse(localStorage.getItem('tour-recent')||'[]')};
function save(){localStorage.setItem('tour-favorites',JSON.stringify([...state.favorites]));localStorage.setItem('tour-recent',JSON.stringify(state.recent.slice(0,8)));updateStats()}
function updateStats(){$('totalCount').textContent=guides.length;$('favoriteCount').textContent=state.favorites.size;$('recentCount').textContent=state.recent.length}
function cityList(){const cities=[...new Set(guides.filter(g=>state.country==='all'||state.country==='favorites'||g.country===state.country).map(g=>g.city))];$('cityRow').innerHTML=cities.map(city=>`<button class="city-button ${state.city===city?'active':''}" data-city="${city}">${city}</button>`).join('');$('cityRow').querySelectorAll('[data-city]').forEach(b=>b.onclick=()=>{state.city=state.city===b.dataset.city?'all':b.dataset.city;render()})}
function matches(g){const q=state.query.trim().toLowerCase(),countryOk=state.country==='all'||state.country==='favorites'||g.country===state.country,favOk=state.country!=='favorites'||state.favorites.has(g.file),cityOk=state.city==='all'||g.city===state.city;return countryOk&&favOk&&cityOk&&(!q||`${g.title}${g.city}`.toLowerCase().includes(q))}
function render(){cityList();const visible=guides.filter(matches);$('guideGrid').innerHTML=visible.map(g=>`<article class="guide-card" tabindex="0" data-file="${encodeURIComponent(g.file)}"><div class="card-top"><span class="country-label">${g.country==='france'?'FRANCE':'SPAIN'}</span><button class="favorite ${state.favorites.has(g.file)?'saved':''}" data-fav="${encodeURIComponent(g.file)}" aria-label="收藏 ${g.title}">${state.favorites.has(g.file)?'★':'☆'}</button></div><h2>${g.title}</h2><p>${g.city} · 中文语音导览</p><div class="card-footer"><span class="play-mark"><span>▶</span>播放导览</span><span>详细版</span></div></article>`).join('');$('emptyState').hidden=visible.length>0;$('guideGrid').querySelectorAll('.guide-card').forEach(card=>{card.onclick=e=>{if(e.target.closest('[data-fav]'))return;play(guides.find(g=>encodeURIComponent(g.file)===card.dataset.file))};card.onkeydown=e=>{if(e.key==='Enter')play(guides.find(g=>encodeURIComponent(g.file)===card.dataset.file))}});$('guideGrid').querySelectorAll('[data-fav]').forEach(btn=>btn.onclick=e=>{e.stopPropagation();const file=decodeURIComponent(btn.dataset.fav);state.favorites.has(file)?state.favorites.delete(file):state.favorites.add(file);save();render()})}
function play(g){if(!g)return;state.current=g;audio.src=`audio/${encodeURIComponent(g.file)}`;audio.currentTime=Number(localStorage.getItem(`progress:${g.file}`)||0);$('nowPlaying').textContent=g.title;$('nowCity').textContent=`${g.city} · ${g.country==='france'?'法国':'西班牙'}`;$('player').hidden=false;state.recent=[g.file,...state.recent.filter(f=>f!==g.file)].slice(0,8);save();cacheAudio(g.file);audio.play().catch(()=>{});render()}
async function cacheAudio(file){if(!('caches' in window))return;const cache=await caches.open(OFFLINE_CACHE);const url=`audio/${encodeURIComponent(file)}`;if(await cache.match(url))return;try{await cache.add(url)}catch(e){console.warn('离线缓存失败',file,e)}}
async function updateOfflineStatus(){if(!('caches' in window)){ $('offlineStatus').textContent='当前浏览器不支持离线缓存';return }const cache=await caches.open(OFFLINE_CACHE);const cached=(await Promise.all(guides.map(g=>cache.match(`audio/${encodeURIComponent(g.file)}`)))).filter(Boolean).length;$('offlineStatus').textContent=cached===guides.length?'已完成离线缓存，可断网播放':`已缓存 ${cached}/${guides.length} 个导览`;$('offlineButton').textContent=cached===guides.length?'已准备好':'下载全部'}
async function downloadAll(){if(!('caches' in window)){updateOfflineStatus();return}const button=$('offlineButton'),progress=$('.offline-progress'),bar=$('offlineProgressBar');button.disabled=true;progress.hidden=false;const cache=await caches.open(OFFLINE_CACHE);let done=0;for(const g of guides){const url=`audio/${encodeURIComponent(g.file)}`;if(!await cache.match(url)){try{const response=await fetch(url);if(!response.ok)throw new Error(response.status);await cache.put(url,response)}catch(e){console.warn('下载失败',g.file,e)}}done++;bar.style.width=`${Math.round(done/guides.length*100)}%`;$('offlineStatus').textContent=`正在准备 ${done}/${guides.length} 个导览`};button.disabled=false;await updateOfflineStatus()}
audio.addEventListener('timeupdate',()=>{if(state.current&&audio.currentTime>2)localStorage.setItem(`progress:${state.current.file}`,String(audio.currentTime))});audio.addEventListener('ended',()=>{if(state.current)localStorage.removeItem(`progress:${state.current.file}`)});
$('backButton').onclick=()=>audio.currentTime=Math.max(0,audio.currentTime-15);$('forwardButton').onclick=()=>audio.currentTime=Math.min(audio.duration||Infinity,audio.currentTime+30);$('closePlayer').onclick=()=>{$('player').hidden=true;audio.pause()};
document.querySelectorAll('[data-country]').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('[data-country]').forEach(b=>b.classList.remove('active'));btn.classList.add('active');state.country=btn.dataset.country;state.city='all';render()});$('searchInput').oninput=e=>{state.query=e.target.value;render()};updateStats();render();
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js');$('offlineButton').onclick=downloadAll;updateOfflineStatus();let deferredPrompt;$('installButton').onclick=()=>deferredPrompt?.prompt();window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installButton').hidden=false});
